services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      # Do lado direito é a porta dentro do container, pra network interna que o docker cria
      # Do lado esquerdo é a porta pública que vai ser acessível por fora do container
      - "${WSRS_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${WSRS_DATABASE_USER}"
      POSTGRES_PASSWORD: "${WSRS_DATABASE_PASSWORD}"
      POSTGRES_DB: "${WSRS_DATABASE_NAME}"
    volumes:
      # Aqui colocamos o diretório dentro do container que eu quero que seja persistido, no caso do postgres é esse path
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${WSRS_PGADMIN_PORT:-8081}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${WSRS_PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${WSRS_PGADMIN_PASSWORD}"
    volumes:
      - pgadmin:/var/lib/pgadmin
    

volumes:
  # O volume é um diretório que é compartilhado entre o container e o host para persistir os dados da aplicação caso o container morra
  db:
    driver: local
  pgadmin:
    driver: local